export const TIMELINE_CONSTANTS = {
  DAY_COLUMN_WIDTH: 80,
  WEEK_COLUMN_WIDTH: 120,
  MONTH_COLUMN_WIDTH: 150,
  ROW_HEIGHT: 64,
  LEFT_PANEL_WIDTH: 200,
  PANEL_SLIDE_WIDTH: 400,
  DEFAULT_VISIBLE_DAYS: 28,
} as const;
